name: Summary Statistics
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      - name: Install Python dependencies.
        env:
          PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
        run: |
          # Install torch first because we need the headers for torch-scatter, etc.
          pip install --no-compile --no-deps `cat requirements.txt | grep torch==`
          # Install pybind11 first because we need the package for fasttr.
          pip install --no-compile --no-deps `cat requirements.txt | grep pybind11==`
          # Install the remaining dependencies.
          pip install --no-compile --no-deps -r requirements.txt
      - name: Lint the code.
        run: flake8
      - name: Run the tests.
        run: pytest --cov=summaries --cov-report=term-missing --cov-fail-under=100
